all:
  hosts:
  children:
    x86_64:
      hosts:
        t630-1:
        atomicpi02:
        lab01:
    aarch64:
      hosts:
        pi4-8748bce1:
  vars:
    ansible_host: "{{ inventory_hostname }}.localdomain"
